const memes = [
    {
      id: 1,
      titulo: "Nazaré Confusa",
      categoria: "Clássico",
      origem: "Novela 'Senhora do Destino'",
      dataCriacao: "2016",
      popularidade: 100,
      tags: ["confusão", "cálculos", "pensativa", "brasileiro"],
      formato: "GIF",
      autor: "Rede Globo",
    },
    {
      id: 2,
      titulo: "Distracted Boyfriend",
      categoria: "Viral",
      origem: "Banco de imagens (Stock photo)",
      dataCriacao: "2017",
      popularidade: 70,
      tags: ["distração", "relacionamento", "ciúmes", "escolha"],
      formato: "Imagem",
      autor: "Antonio Guillem",
    },
    {
      id: 3,
      titulo: "Grumpy Cat",
      categoria: "Clássico",
      origem: "Foto de um gato (Tardar Sauce)",
      dataCriacao: "2012",
      popularidade: 80,
      tags: ["mau humor", "gato", "reclamação", "sarcasmo"],
      formato: "Imagem",
      autor: "Tabatha Bundesen",
    },
    {
      id: 4,
      titulo: "Stonks",
      categoria: "Reação",
      origem: "Meme Man / Surreal Memes",
      dataCriacao: "2017",
      popularidade: 70,
      tags: ["finanças", "investimentos", "negócios", "erro"],
      formato: "Imagem",
      autor: "Desconhecido",
    },
    {
      id: 5,
      titulo: "This is Fine",
      categoria: "Reação",
      origem: "Webcomic 'Gunshow'",
      dataCriacao: "2013",
      popularidade: 80,
      tags: ["caos", "negação", "problemas", "calma"],
      formato: "Imagem",
      autor: "KC Green",
    },
    {
      id: 6,
      titulo: "Mulher Gritando com um Gato (Woman Yelling at a Cat)",
      categoria: "Viral",
      origem: "Combinação de duas imagens",
      dataCriacao: "2019",
      popularidade: 90,
      tags: ["discussão", "confusão", "gato", "acusação"],
      formato: "Imagem",
      autor: "Combinação anônima",
    },
    {
      id: 7,
      titulo: "Caneta Azul",
      categoria: "Brasileiro",
      origem: "Vídeo viral de Manoel Gomes",
      dataCriacao: "2019",
      popularidade: 60,
      tags: ["música", "viral", "hit", "maranhense"],
      formato: "Vídeo",
      autor: "Manoel Gomes",
    },
    {
      id: 8,
      titulo: "Doge",
      categoria: "Clássico",
      origem: "Foto de um cachorro Shiba Inu",
      dataCriacao: "2013",
      popularidade: 70,
      tags: ["cachorro", "wow", "such meme", "muito legal"],
      formato: "Imagem",
      autor: "Atsuko Sato",
    },
    {
      id: 9,
      titulo: "Bora Bill",
      categoria: "Brasileiro",
      origem: "Vídeo de jogo de várzea",
      dataCriacao: "2022",
      popularidade: 50,
      tags: ["futebol", "viral", "família", "cearense"],
      formato: "Vídeo",
      autor: "Desconhecido",
    },
    {
      id: 10,
      titulo: "Is this a pigeon?",
      categoria: "Reação",
      origem: "Anime 'The Brave Fighter of Sun Fighbird'",
      dataCriacao: "2011",
      popularidade: 60,
      tags: ["anime", "pergunta", "erro", "confusão"],
      formato: "Imagem",
      autor: "Sunrise (estúdio)",
    },
  ];
  
  export default { memes };